apiVersion: v1
kind: Service
metadata:
  name: nayan-hpa-svc
spec:
  ports:
  - port: 31001
    nodePort: 31004
    targetPort: http-port
    protocol: TCP
  selector:
    app: nayan-hpa
  type: NodePort
