apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nayan-hpa-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nayan-hpa
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
