apiVersion: apps/v1
kind: Deployment
metadata:
  name: nayan-deploy
  labels:
    app: nayan-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nayan-deploy
  template:
    metadata:
      labels:
        app: nayan-deploy
    spec:
      containers:
      - name: nayan-deploy
        image: amitvashist7/k8s-tiny-web 
        imagePullPolicy: IfNotPresent
        ports:
          - name: nayan-app-port
            containerPort: 80
        volumeMounts:
        - name: cred-volume
          mountPath: /etc/creds
          readOnly: true
        - name: cred-volume-2
          mountPath: /etc/mysecrets
          readOnly: true
      volumes:
      - name: cred-volume
        secret:
          secretName: nayan-db-secret
      - name: cred-volume-2
        secret:
          secretName: nayan-db-secret
