apiVersion: apps/v1
kind: Deployment
metadata:
  name: nayan-deploy
  labels:
    app: nayan-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nayan-deploy
  template:
    metadata:
      labels:
        app: nayan-deploy
    spec:
      containers:
      - name: nayan-deploy
        image: amitvashist7/mypython-web-app:v4 
        imagePullPolicy: IfNotPresent
        ports:
          - name: nayan-app-port
            containerPort: 8081
