apiVersion: v1
kind: ReplicationController
metadata:
  name: nayan-k8s-rc
spec:
  replicas: 4
  selector:
    app: selector
  template:
    metadata:
      labels:
        app: selector
    spec:
      containers:
        - name: nayan-k8s-rc
          image: nginx
          ports:
            - name: http-port
              containerPort: 80
