apiVersion: v1
kind: Service
metadata:
  name: nayan-deploy-svc-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external-facing
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: nayan-deploy
