apiVersion: v1
kind: Service
metadata:
  name: nayan-deploy-svc
spec:
  ports:
  - port: 31005
    nodePort: 30001
    targetPort: nayan-app-port
    protocol: TCP
  selector:
    app: nayan-deploy
  type: NodePort 
